

@usertoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2MwMDM5NDdhNGM3ODZlZWY4ODdlMSIsImlhdCI6MTY0MDg0MzA2MywiZXhwIjoxNjQwOTI5NDYzfQ.CqnWQ0MjYrwnIunkgnlPG7URNduB8W-DG4YhsspUd64
POST  https://teamwork-ecommerce.herokuapp.com/product/favorite/add
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2Q1NTcxZGZlZDI2ODBhNDA1MzhhNyIsImlhdCI6MTY0MDg0NjcyMiwiZXhwIjoxNjQwOTMzMTIyfQ.BFQq9AvGO9WPiQ1IHm1rNUmlG3pTRf_DdyQ9iDRvkYA

{
 "title": "Amethyst Bracelet",
 "description": "Purple Bracelet For Women",
 "price": 25.20,
 "ammount": 60,
 "rating": 4.6,
 "category": "Handmade"
}