
POST https://teamwork-ecommerce.herokuapp.com/product/favorite
content-type: application/json

{
 "userId": "61c2d8ac79089ae7cced172a"
}

# {
#  "userId": "61c1bc3a3a6ea5c0f5dc0ea7",
#  "title": "Farm Table",
#  "description": "Thick-wrapped farm table stained in beautiful espresso",
#  "price": 970.00,
#  "ammount": 7,
#  "rating": 4.8,
#  "category": "Furniture"
# }